Vagrant.configure("2") do |config|
  config.vm.provision "docker"
  config.vm.provision "shell", path: "install_k8s.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus= 2
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  config.vm.define "k8s1" do |k8s1|
    k8s1.vm.box = "centos/7"
    k8s1.vm.hostname = 'k8s1'
    k8s1.vm.network "private_network", ip: "192.168.99.100"
  end

  config.vm.define "k8s2" do |k8s2|
    k8s2.vm.box = "centos/7"
    k8s2.vm.hostname = 'k8s2'
    k8s2.vm.network "private_network", ip: "192.168.99.101"
  end

  config.vm.define "k8s3" do |k8s3|
    k8s3.vm.box = "centos/7"
    k8s3.vm.hostname = "k8s3"
    k8s3.vm.network "private_network", ip: "192.168.99.102"
  end
end


